Electric-Coin-Company/kotlin-bip39

gradle.properties, lib/src/jvmMain/kotlin/cash/z/ecc/android/crypto/FallbackProvider.kt, lib/src/jvmMain/kotlin/cash/z/ecc/android/crypto/Pbkdf2Sha512.kt, lib/src/jvmTest/kotlin/cash/z/ecc/android/bip39/MnemonicsTest.kt, lib/src/jvmTest/kotlin/cash/z/ecc/android/bip39/ReadmeExamplesTest.kt
Fixed existing warnings, which included:
- Suppressing a deprecation warning for Java 9, as we have to maintain compatibility with Java 8 for Android
- Using a new Kotlin API introduced in Kotlin 1.5
- Removed unused local variables in the tests
=> [#25] Enable strict Kotlin compiler warnings

README.md
Jcenter is deprecated and library is also published to MavenCentral
=> [#12] Remove reference to Jcenter

.github/PULL_REQUEST_TEMPLATE.md
=> [#34] Delete “run demo app” from review checklist

.github/actions/setup/action.yml, README.md
Temurin/Adoptium is the default used by Gradle toolchains, and they now have both Java 11 and 17 ARM support for Macs
=> [#49] Switch to Adoptium JDK

.github/dependabot.yml
=> [#54] Configure dependabot for GitHub Actions

.github/ISSUE_TEMPLATE/dependency.md, .github/ISSUE_TEMPLATE/feature-request.md
=> [#45] Fix typos in github templates

.github/workflows/deploy-snapshot.yml
=> [#55] Rename default branch

.github/workflows/deploy-snapshot.yml
=> [#71] Fix environment for snapshot deployment

.github/dependabot.yml
=> [#75] Run dependabot on composite workflows

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
The output path is different for a Kotlin project compared to an Android project, so this corrects that.
=> [#73] Attach build output for GitHub Actions

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, bip39-lib/build.gradle.kts, docs/PUBLISHING.md, gradle.properties
- Remove `IS_RELEASE_SIGNING_ENABLED` as it didn’t do what was expected.  It just made signing optional and didn’t toggle signing off.
- Removed passing signing key for snapshot deployments in deployment
- Pass signing key for maven local deployment for release deployment
=> [#52] Fix signing maven publications

CHANGELOG.md, README.md, docs/Build integrity.md, docs/PUBLISHING.md, gradle.properties
Bumping the version ensures that subsequent snapshot deployments are bumped to 1.0.4-SNAPSHOT
=> Prepare for development of next release

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, README.md, bip39-lib/build.gradle.kts, docs/PUBLISHING.md
Previously just the multiplatform metadata was being published, which means the JVM version of the library didn't get published.
=> [#95] Fix publishing all variants

gradle.properties
Bumping the version ensures that subsequent snapshot deployments are bumped to 1.0.4-SNAPSHOT
=> Prepare development for 1.0.5 release

gradle/wrapper/gradle-wrapper.properties
=> [#99] Gradle 7.5.1

CHANGELOG.md
> **Note**
[^3]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes …
=> Changelog for 1.0.5

CHANGELOG.md, gradle.properties
Closes #225
> **Note**
[^3]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as …
=> [#225] Bip-39 release v1.0.6

CHANGELOG.md
Closes #269
> **Note**
[^3]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as …
=> [#269] Release v1.0.8

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml
Closes #295
> **Note**
[^3]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as …
=> [#295] Resolve CI actions deprecations

gradle.properties
Closes #320
> **Note**
[^3]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as …
=> [#320] Library version 1.0.9
